export interface Message {
    date: Date
    sender: string
    content: string
    isSystem: boolean
}

export interface ParsedChat {
    messages: Message[]
    participants: string[]
    dateRange: {
        start: Date
        end: Date
    }
    isGroup: boolean
}

// Matches: [DD/MM/YY, HH.MM.SS] or [D/M/YY, HH.MM.SS]
const MESSAGE_REGEX = /^\[(\d{1,2}\/\d{1,2}\/\d{2,4}),\s(\d{1,2}\.\d{2}\.\d{2})\]\s/

// System message patterns to skip from participant counting
const SYSTEM_MESSAGE_PATTERNS = [
    /Messages and calls are end-to-end encrypted/,
    /added you/,
    /added \w/,
    /created this group/,
    /changed the subject/,
    /changed this group/,
    /left$/,
    /removed$/,
    /joined using this group/,
    /changed their phone number/,
    /Missed voice call/,
    /Missed video call/,
    /Voice call/,
    /Video call/,
    /Only messages that mention/,
    /Messages are generated by AI/,
    /Waiting for this message/,
]

function isSystemSender(sender: string): boolean {
    // Healing💃🏼, Meta AI, etc. are often system senders
    // But we detect system messages by content, not sender
    return false
}

function isSystemMessage(content: string): boolean {
    return SYSTEM_MESSAGE_PATTERNS.some(p => p.test(content))
}

function parseDate(dateStr: string, timeStr: string): Date {
    // dateStr: DD/MM/YY or DD/MM/YYYY
    // timeStr: HH.MM.SS
    const dateParts = dateStr.split('/')
    const timeParts = timeStr.split('.')

    let year = parseInt(dateParts[2])
    if (year < 100) year += 2000

    const month = parseInt(dateParts[1]) - 1 // 0-indexed
    const day = parseInt(dateParts[0])
    const hours = parseInt(timeParts[0])
    const minutes = parseInt(timeParts[1])
    const seconds = parseInt(timeParts[2])

    return new Date(year, month, day, hours, minutes, seconds)
}

export function parseWhatsAppChat(raw: string): ParsedChat {
    // Normalize line endings
    const text = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n')
    const lines = text.split('\n')

    const messages: Message[] = []
    let current: Message | null = null

    for (const line of lines) {
        const match = line.match(MESSAGE_REGEX)

        if (match) {
            // Save previous message
            if (current) {
                messages.push(current)
            }

            const dateStr = match[1]
            const timeStr = match[2]
            const date = parseDate(dateStr, timeStr)
            // Rest of line after the timestamp
            const rest = line.slice(match[0].length)

            // Remove leading special char ‎ (Unicode LTR mark)
            const cleanRest = rest.replace(/^\u200e/, '').trim()

            // Check if there's a sender: "Name: message"
            const colonIdx = cleanRest.indexOf(': ')
            let sender: string
            let content: string

            if (colonIdx !== -1) {
                sender = cleanRest.slice(0, colonIdx).trim()
                content = cleanRest.slice(colonIdx + 2).trim()
            } else {
                // System message with no sender colon
                sender = ''
                content = cleanRest
            }

            const system = sender === '' || isSystemMessage(content)

            current = {
                date,
                sender,
                content,
                isSystem: system,
            }
        } else if (current && line.trim() !== '') {
            // Continuation of previous multi-line message
            current.content += '\n' + line
        }
    }

    // Push last message
    if (current) {
        messages.push(current)
    }

    // Build participants (exclude empty senders & deduplicate)
    const participantSet = new Set<string>()
    for (const msg of messages) {
        if (!msg.isSystem && msg.sender) {
            // Clean ~ prefix (some phones add it)
            const cleaned = msg.sender.startsWith('~ ')
                ? msg.sender.slice(2)
                : msg.sender
            participantSet.add(cleaned)
        }
    }
    const participants = Array.from(participantSet)

    // Also fix senders in messages
    for (const msg of messages) {
        if (msg.sender.startsWith('~ ')) {
            msg.sender = msg.sender.slice(2)
        }
    }

    const realMessages = messages.filter(m => !m.isSystem && m.sender)
    const dates = realMessages.map(m => m.date)
    const start = dates.length > 0 ? new Date(Math.min(...dates.map(d => d.getTime()))) : new Date()
    const end = dates.length > 0 ? new Date(Math.max(...dates.map(d => d.getTime()))) : new Date()

    return {
        messages: realMessages,
        participants,
        dateRange: { start, end },
        isGroup: participants.length > 2,
    }
}
